apiVersion: v1
kind: Service
metadata:
  name: monitoring-influxdb
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: InfluxDB
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    k8s-app: influxdb

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-influxdb-v2
  namespace: kube-system
  labels:
    k8s-app: influxdb
    version: v2
    kubernetes.io/cluster-service: 'true'
spec:
  replicas: 1
  selector:
    k8s-app: influxdb
    version: v2
  template:
    metadata:
      labels:
        k8s-app: influxdb
        version: v2
        kubernetes.io/cluster-service: 'true'
    spec:
      containers:
      - image: gcr.io/google_containers/heapster_influxdb:v0.4
        name: influxdb
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8083
          hostPort: 8083
        - containerPort: 8086
          hostPort: 8086
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: "/data"
      volumes:
      - name: influxdb-persistent-storage
        emptyDir: {}
